CREATE DATABASE MOVIE_COMPANY;

USE MOVIE_COMPANY;

CREATE TABLE DIRECTORS (
    ID        INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
    Firstname VARCHAR(20) NULL,
    Lastname  VARCHAR(20) NULL
    );

CREATE TABLE MOVIES
(
    ID           INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
    TITLE        VARCHAR(20) NULL,
    RELEASE_YEAR INT         NULL,
    GENRE        VARCHAR(20) NULL,
    ACTORID      INT         NULL,
    DIRECTORID   INT         NULL,
    FOREIGN KEY (DIRECTORID) REFERENCES DIRECTORS (ID)
);

CREATE TABLE ACTORS (
    ID         INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
    Firstname  VARCHAR(20) NULL,
    Lastname   VARCHAR(20) NULL
);

CREATE TABLE MOVIE_ACTORS_ASSOCIATION (
    MOVIEID int null,
    ACTORID int null,
foreign key (MOVIEID) references MOVIES(ID),
foreign key (ACTORID) references ACTORS(ID)
);

insert into DIRECTORS (FIRSTNAME, LASTNAME) value ('STEVEN','SPIELBERG');
insert into DIRECTORS (FIRSTNAME, LASTNAME) value ('MARTIN','SCORSESE');
insert into DIRECTORS (FIRSTNAME, LASTNAME) value ('ALFRED','HITCHCOCK');
insert into DIRECTORS (FIRSTNAME, LASTNAME) value ('FRANCIS','COPPOLA');
insert into DIRECTORS (FIRSTNAME, LASTNAME) value ('WOODY','ALLEN');
insert into DIRECTORS (FIRSTNAME, LASTNAME) value ('BILLY','WILDER');

insert into MOVIES (TITLE, RELEASE_YEAR, GENRE,ACTORID,DIRECTORID) values  ('JURASSIC PARK', 2009,'ACTION',1,1);
insert into MOVIES (TITLE, RELEASE_YEAR, GENRE,ACTORID, DIRECTORID) values  ('PSYCHO', 1978, 'HORROR',3,2);
insert into MOVIES (TITLE, RELEASE_YEAR, GENRE,ACTORID,DIRECTORID) values  ('SPARTACUS', 1966, 'ADVENTURE',4,1);
insert into MOVIES (TITLE, RELEASE_YEAR, GENRE,ACTORID,DIRECTORID) values  ('THE GODFATHER', 1983, 'CRIME',5,6);
insert into MOVIES (TITLE, RELEASE_YEAR, GENRE,ACTORID,DIRECTORID) values  ('TAXI DRIVER', 1976, 'ROMANCE',2,2);
insert into MOVIES (TITLE, RELEASE_YEAR, GENRE,ACTORID,DIRECTORID) values  ('SCHINDLERS_LIST', 2001, 'WAR',6,1);
insert into MOVIES (TITLE, RELEASE_YEAR, GENRE,ACTORID,DIRECTORID) values  ('HAPPY GILMORE', 2015, 'COMEDY',1,6);
insert into MOVIES (TITLE, RELEASE_YEAR, GENRE,ACTORID,DIRECTORID) values  ('TOMMY BOY', 2015, 'COMEDY',3,4);

insert into ACTORS (FIRSTNAME, LASTNAME) value ('JACK','NICHOLSON');
insert into ACTORS (FIRSTNAME, LASTNAME) value ('MARLON','BRANDO');
insert into ACTORS (FIRSTNAME, LASTNAME) value ('AL','PACINO');
insert into ACTORS (FIRSTNAME, LASTNAME) value ('DUSTIN','HOFFMAN');
insert into ACTORS (FIRSTNAME, LASTNAME) value ('TOM','HANKS');
insert into ACTORS (FIRSTNAME, LASTNAME) value ('ANTHONY','HOPKINS');


select ACTORS.firstname, ACTORS.lastname
from ACTORS
inner join MOVIES ON MOVIES.ACTORID = ACTORS.ID
WHERE GENRE = 'COMEDY';

SELECT * FROM DIRECTORS WHERE (FIRSTNAME,LASTNAME) = ('STEVEN','SPIELBERG');

select DIRECTORS.firstname, DIRECTORS.lastname, MOVIES.TITLE, MOVIES.GENRE
from DIRECTORS
INNER join MOVIES ON MOVIES.DIRECTORID = DIRECTORS.ID
where RELEASE_YEAR = 2015;